service: chatgpt-serverless-discord-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1


plugin:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:
  api:
    handler: handler.handle
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
