service: chatgpt-serverless-discord-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: handler.handle
    events:
      - httpApi:
          path: /
          method: get
