service: chatgpt-serverless-discord-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  architecture: arm64 # ARM이 X86보다 조금이라도 쌉니다..


plugin:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:
  api:
    handler: handler.handle
    events:
      - httpApi:
          path: /
          method: any

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
